AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  coinChange:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: coinChange/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Events:
        Api:
          Type: Api
          Properties:
            Path: /change
            Method: any
